apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nbigm1cmv-python 
  janus-idp.io/tekton: nbigm1cmv-python
  backstage.io/kubernetes-id: nbigm1cmv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nbigm1cmv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  